import { NextResponse } from "next/server";
import { connectDB } from "@/lib/db";
import Test from "@/models/Test";
import Result from "@/models/Result";
import User from "@/models/User";
import Course from "@/models/Course";
import Enrollment from "@/models/Enrollment"; // IMPORT ADDED

export async function POST(req) {
  try {
    await connectDB();

    // 1. Course aur User dhoondho
    const course = await Course.findOne();
    const user = await User.findOne({ role: "student" }) || await User.findOne();

    if (!course || !user) {
        return NextResponse.json({ error: "Please create at least 1 Course and 1 User first!" }, { status: 400 });
    }

    const courseId = course._id;
    const userId = user._id;

    console.log(`Seeding data for Course: ${course.title} and User: ${user.fullName}`);

    // --- FIX: Create Enrollment (Zaruri hai Exam Start karne ke liye) ---
    await Enrollment.findOneAndUpdate(
        { courseId, studentId: userId },
        { courseId, studentId: userId, enrolledAt: new Date() },
        { upsert: true, new: true }
    );

    // --- CLEANUP OLD TESTS ---
    await Test.deleteMany({ courseId: courseId, description: /seed/i }); 
    await Result.deleteMany({ studentId: userId });

    // --- CREATE DUMMY TESTS ---

    // 1. LIVE EXAM
    await Test.create({
        title: "Physics Mock Test - Live",
        description: "This is a live test generated by seed.",
        courseId,
        type: "mcq",
        scheduledAt: new Date(Date.now() - 1000 * 60 * 10), // 10 min pehle shuru hua
        duration: 60,
        totalMarks: 20,
        status: "live",
        questions: [
            { questionText: "Unit of Force?", options: ["Newton", "Joule", "Watt", "Pascal"], correctOption: 0, marks: 4 },
            { questionText: "Speed of light?", options: ["3x10^8 m/s", "3x10^6 m/s", "Sound", "Infinite"], correctOption: 0, marks: 4 },
            { questionText: "E=mc^2 related to?", options: ["Newton", "Einstein", "Bohr", "Tesla"], correctOption: 1, marks: 4 },
            { questionText: "Freezing point of water?", options: ["0 C", "100 C", "-10 C", "20 C"], correctOption: 0, marks: 4 },
            { questionText: "Shape of Earth?", options: ["Flat", "Round", "Square", "Triangle"], correctOption: 1, marks: 4 }
        ]
    });

    // 2. UPCOMING EXAM
    await Test.create({
        title: "Chemistry Weekly Test",
        description: "Upcoming test generated by seed.",
        courseId,
        type: "mcq",
        scheduledAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2), // 2 din baad
        duration: 45,
        totalMarks: 50,
        status: "scheduled",
        questions: [{ questionText: "H2O is?", options: ["Water", "Gas", "Metal", "Acid"], correctOption: 0 }]
    });

    // 3. COMPLETED EXAM (Missed)
    await Test.create({
        title: "Maths Surprise Test",
        description: "Ended test generated by seed.",
        courseId,
        type: "mcq",
        scheduledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5), // 5 din pehle
        duration: 30,
        totalMarks: 30,
        status: "completed",
        questions: [{ questionText: "2+2=?", options: ["3", "4", "5", "6"], correctOption: 1 }]
    });

    return NextResponse.json({ 
        success: true, 
        message: "Data seeded & Enrollment fixed!",
        data: {
            course: course.title,
            student: user.fullName,
            status: "Enrolled Successfully"
        }
    });

  } catch (error) {
    console.error("Seed Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}